### ISSUE TITLE
Additional Data

### ISSUE THREAD

**Issue by rblazquez** [agorapulse/grails-raven#16]
After read log4j and raven integration i see that i can use MDC to send information to the "Additional Data" tag. It should be as simple as:

MDC.push("key", "value")
logger.error("error message") 

Is this supported by grails-raven or should i use a different way to send extra data?

Thanks in advance.

**Comment by benorama** [comment]
You might give it a try, but since we are using raven-java (log4j) under the hood, it might work:
https://github.com/getsentry/raven-java/tree/master/raven-log4j

**Comment by rblazquez** [comment]
I've tried with v0.5.8 and it seems not working ... what would be the correct way to send this additional data? ... note that this are no tags to filter but just extra information.

**Comment by vmpj** [comment]
The following works with 0.5.8:

    class RavenFilters {
        def ravenClient

        def filters = {
            all(controller:'*', action:'*') {
                before = {
                    Map userData = [is_authenticated: true, custom_key_2: "custom value 2"]
                    ravenClient?.setUserData(userData)
                }
            }
        }
    }
