### ISSUE TITLE
java.lang.ClassNotFoundException: net.kencochrane.raven.event.Event

### ISSUE THREAD

**Issue by andrebrov** [agorapulse/grails-raven#5]
Hello,
I tried to switch to Raven plugin 6.0.0 so I've added to my BuildConfig.groovy next line:
compile ':raven:0.5.8'
After that I got next error:
ERROR context.GrailsContextLoaderListener - Error initializing the application: Error creating bean with name 'sentryAppender': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [grails.plugins.raven.GrailsLog4jSentryAppender]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: net/kencochrane/raven/event/Event
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sentryAppender': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [grails.plugins.raven.GrailsLog4jSentryAppender]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: net/kencochrane/raven/event/Event
Can you pls help?

**Comment by benorama** [comment]
This is an error we also have on only one of our 8 apps, since the upgrade to Raven 6.0.0 (java lib).
It looks like a class loading issue.

I would recommend to stick with the legacy 0.5.8 (100% groovy based) if you can't solve the issue.

**Comment by CyrilCarmien** [comment]
Hi, just to say that I have the exact same problem on my projects :/ switching to 0.5.8 does correct this mistake

**Comment by mhuebner** [comment]
Same issue!

**Comment by Nr9** [comment]
Same issue!
